apiVersion: apps/v1
kind: Deployment    
metadata:
  name: my-nginx
  labels:
    app: nginx
spec:
  replicas: 3  # Run 2 instanc es of Nginx      
  selector:
    matchLabels:
      app: nginx  # Select pods with label "nginx"    
  template:
    metadata:
      labels:
        app: nginx  # Label applied to created pods 
    spec:
      containers:
      - name: nginx
        image: nginx:latest  # Pulls the latest nginx image
        ports:
        - containerPort: 80  # Exposes port 80
